version: '2'
services:
    checkpoint-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/checkpoint/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=checkpoint
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
